import { createVuetify } from "vuetify";
import {
  VBtn,
  VApp,
  VLayout,
  VAppBar,
  VNavigationDrawer,
  VList,
  VListItem,
  VAvatar,
  VIcon,
  VMain,
  VCard,
  VCardActions,
  VCardTitle,
  VCardText,
  VSelect,
  VTable,
  VTooltip,
  VProgressCircular,
  VTextField,
  VPagination,
  VSlideXTransition,
  VChipGroup,
  VChip,
  VFabTransition,
  VHover,
  VDialog,
  VTextarea,
  VImg,
  VCheckbox,
  VSnackbar,
  VTabs,
  VTab,
  VWindow,
  VWindowItem,
  VDataTable,
  VSpeedDial,
  VFab,
} from "vuetify/components";

export default defineNuxtPlugin((nuxtApp) => {
  const vuetify = createVuetify({
    ssr: true,
    theme: {
      defaultTheme: "musicMuseDark",
      themes: {
        musicMuseDark: {
          dark: true,
          colors: {
            primary: "#BA68C8",
            secondary: "#3F51B5",
            background: "#191414",
            info: "#2196F3",
            error: "#FF5722",
            success: "#4CAF50",
            warning: "#FFC107",
          },
        },
      },
    },
    components: {
      VBtn,
      VLayout,
      VAppBar,
      VNavigationDrawer,
      VList,
      VListItem,
      VAvatar,
      VIcon,
      VMain,
      VCard,
      VCardActions,
      VCardTitle,
      VCardText,
      VSelect,
      VTable,
      VTooltip,
      VProgressCircular,
      VTextField,
      VPagination,
      VSlideXTransition,
      VFabTransition,
      VChipGroup,
      VChip,
      VApp,
      VHover,
      VDialog,
      VTextarea,
      VImg,
      VCheckbox,
      VSnackbar,
      VTabs,
      VTab,
      VWindow,
      VWindowItem,
      VDataTable,
      VSpeedDial,
      VFab,
    },
  });

  nuxtApp.vueApp.use(vuetify);
});
